# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sat Aug 02 18:24:36 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(186, 329)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("border-color: rgb(255, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.list = QtGui.QListWidget(self.centralwidget)
        self.list.setObjectName("list")
        self.verticalLayout_2.addWidget(self.list)
        self.filter = QtGui.QLineEdit(self.centralwidget)
        self.filter.setObjectName("filter")
        self.verticalLayout_2.addWidget(self.filter)
        self.button = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button.sizePolicy().hasHeightForWidth())
        self.button.setSizePolicy(sizePolicy)
        self.button.setMinimumSize(QtCore.QSize(64, 64))
        self.button.setText("")
        self.button.setIconSize(QtCore.QSize(48, 48))
        self.button.setCheckable(False)
        self.button.setChecked(False)
        self.button.setFlat(True)
        self.button.setObjectName("button")
        self.verticalLayout_2.addWidget(self.button)
        self.rec_group = QtGui.QFrame(self.centralwidget)
        self.rec_group.setObjectName("rec_group")
        self.rec_layout = QtGui.QHBoxLayout(self.rec_group)
        self.rec_layout.setContentsMargins(0, 0, 0, 0)
        self.rec_layout.setObjectName("rec_layout")
        self.verticalLayout_2.addWidget(self.rec_group)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 186, 18))
        self.menuBar.setObjectName("menuBar")
        self.menuRecorder = QtGui.QMenu(self.menuBar)
        self.menuRecorder.setObjectName("menuRecorder")
        MainWindow.setMenuBar(self.menuBar)
        self.actionRecording = QtGui.QAction(MainWindow)
        self.actionRecording.setObjectName("actionRecording")
        self.actionPlaylist = QtGui.QAction(MainWindow)
        self.actionPlaylist.setObjectName("actionPlaylist")
        self.actionRecord = QtGui.QAction(MainWindow)
        self.actionRecord.setObjectName("actionRecord")
        self.actionPause = QtGui.QAction(MainWindow)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionClipboard = QtGui.QAction(MainWindow)
        self.actionClipboard.setObjectName("actionClipboard")
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setObjectName("actionPlay")
        self.actionRemove = QtGui.QAction(MainWindow)
        self.actionRemove.setObjectName("actionRemove")
        self.actionShowLibrary = QtGui.QAction(MainWindow)
        self.actionShowLibrary.setObjectName("actionShowLibrary")
        self.actionShowRecorder = QtGui.QAction(MainWindow)
        self.actionShowRecorder.setObjectName("actionShowRecorder")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuRecorder.addAction(self.actionClipboard)
        self.menuRecorder.addSeparator()
        self.menuRecorder.addAction(self.actionRecord)
        self.menuRecorder.addAction(self.actionPause)
        self.menuRecorder.addAction(self.actionSave)
        self.menuRecorder.addSeparator()
        self.menuRecorder.addAction(self.actionShowLibrary)
        self.menuRecorder.addAction(self.actionPlay)
        self.menuRecorder.addAction(self.actionRemove)
        self.menuRecorder.addSeparator()
        self.menuRecorder.addAction(self.actionShowRecorder)
        self.menuBar.addAction(self.menuRecorder.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.list, self.filter)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "mauto", None, QtGui.QApplication.UnicodeUTF8))
        self.filter.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Filter...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRecorder.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecording.setText(QtGui.QApplication.translate("MainWindow", "Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlaylist.setText(QtGui.QApplication.translate("MainWindow", "Playlist", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecord.setText(QtGui.QApplication.translate("MainWindow", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClipboard.setText(QtGui.QApplication.translate("MainWindow", "From clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay.setText(QtGui.QApplication.translate("MainWindow", "Play...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowLibrary.setText(QtGui.QApplication.translate("MainWindow", "Show Library", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowRecorder.setText(QtGui.QApplication.translate("MainWindow", "Show Recorder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save as...", None, QtGui.QApplication.UnicodeUTF8))

